### ISSUE TITLE
Avoid use of JMeq_eq

### ISSUE THREAD

**Issue by Lysxia** [snu-sf/paco#36] opened 2020-12-03 17:07 UTC
Paco uses the `JMeq_eq` axiom (`JMeq x y -> x = y`) in the `pcofix` tactic (in `pacotac_internal.v`). The gist of what it's doing is to reshape the goal into a form where the `pacoN_acc` lemma can be applied, and `JMeq_eq` is used somewhere in this transformation. I'm wondering whether this can be simplified, in a way that doesn't use `JMeq_eq`.

As I understand it, `pcofix` needs to do the following.

Initial goal:

```
===================
forall x y z, hyps -> paco2 gf bot2 (f x y) (g z)
```

"uncurry" the goal

```
===================
forall a b, (exists x y z, hyps /\ existT _ a b = existT _ (f x y) (g z)) -> paco2 gf bot2 a b
```

apply `paco2_acc`

```
r : forall a b, Prop
COFIX : forall a b, (exists x y z, hyps /\ existT _ a b = existT _ (f x y) (g z)) -> r a b
===================
forall a b, (exists x y z, hyps /\ existT _ a b = existT _ (f x y) (g z)) -> paco2 gf r a b
```

"curry" the goal

```
r : forall a b, Prop
COFIX : forall a b, (exists x y z, hyps /\ existT _ a b = existT _ (f x y) (g z)) -> r a b
===================
forall x y z, hyps -> paco2 gf r (f x y) (g z)
```

"curry" the hypothesis

```
r : forall a b, Prop
COFIX : forall x y z, hyps -> r (f x y) (g z)
===================
forall x y z, hyps -> paco2 gf r (f x y) (g z)
```

`JMeq_eq` may seem necessary to rewrite between `R a b` and `R (f x y) (g z)` given only `existT _ a b = existT _ (f x y) (g z)`, but this can actually be done without axioms by simply converting `R a b` to `R (projT1 (existT _ a b)) (projT2 (existT _ a b))`, and then rewriting with the above.

I think all of these steps are relatively straightforward (in fact I've already done most of the work once https://github.com/snu-sf/paco/blob/fb5be107330531e085405dbbfd60f6cb2fd2ce29/metasrc/paco_sigma.v#L309-L373, it is currently commented out because of definitions that no longer exist, but I can restore and polish the whole thing), that's why I'm a bit surprised at the complexity of the existing definition of the `pcofix` tactic. Am I missing some nuance about what `pcofix` needs to do?

**Comment by minkiminki** [comment] 2020-12-04 13:05
Really Cool!!! Do you have a working version?
@gilhur may be the only one who understands how current `pcofix` works.

**Comment by Lysxia** [comment] 2020-12-10 21:33
Here's a working version: https://gist.github.com/Lysxia/886d753900f981210dd5cdb6343bc89f

One difference from what I described initially is that it's a little more convenient to use the following lemma, equivalent to [paco3_acc]:

```coq
Parameter paco3_accF
  : forall {T0 : Type} {T1 : forall a : T0, Type} {T2 : forall (a : T0) (b : T1 a), Type}
      (gf : rel3 T0 T1 T2 -> rel3 T0 T1 T2) (r0 : rel3 T0 T1 T2)
      (X : Type)
      (f0 : X -> T0) (f1 : forall x : X, T1 (f0 x)) (f2 : forall x : X, T2 (f0 x) (f1 x)),
      (forall r : rel3 T0 T1 T2,
        (forall x, r (f0 x) (f1 x) (f2 x)) ->
        forall x : X, paco3 gf r (f0 x) (f1 x) (f2 x)) ->
      forall x : X, paco3 gf r0 (f0 x) (f1 x) (f2 x).
```

One remaining thing I haven't managed to do is to preserve the variable names from the initial goal in the coinduction hypothesis. Apart from that, it should work fine.

**Comment by gilhur** [comment] 2020-12-17 10:20
Hi Lysxia, I think it might be possible to develop a simpler version of paco tactics as you did.
Please understand that I developed the tactics in 2012 :)
Can you give me some hints about what are telescope and teleprop?
Currently I cannot even compile your code due to tele things.

**Comment by Lysxia** [comment] 2020-12-17 13:42
Thanks @gilhur, that's encouraging to hear. See this other gist with an updated and further simplified version https://gist.github.com/Lysxia/886d753900f981210dd5cdb6343bc89f (the "tele" stuff was just some inductive equivalent to nested sigma types)

**Comment by gilhur** [comment] 2020-12-28 12:17
Thanks @Lysxia. It works well!
I revised it to preserve the variable names in the coinductive hypothesis (see below).
I will upgrade the paco library with this simplified approach.
```coq
Ltac pcofix_ self pack_goal0 unpack_goal0 revert_tmp0 :=
  hnf;
  lazymatch goal with
  | [ |- forall H : ?X, _ ] =>
    (* 1. *)
    let H := fresh H in
    intros H;
    let pack_goal := (revert H; apply curry_sig; pack_goal0) in
    let unpack_goal H0 := ltac:(unpack_goal0 H0; destruct H0 as [H H0]; cbn [projT1 projT2]) in
    let revert_tmp := revert H; revert_tmp0 in
    pcofix_ self pack_goal unpack_goal revert_tmp
  | _ =>
    let r := fresh "r" in
    let self := fresh self in
    let tmp_self := fresh "_pacotmp_self_" in
    let tmp_hyp := fresh "_pacotmp_hyp_" in
    let tmp_type := fresh "_pacotmp_type_" in
    (* 2. pack_goal *) pose proof (tmp_hyp := tt); revert tmp_hyp; pack_goal0;
    (* 3. paco_acc *) apply_paco_acc; intros r tmp_self;
    (* 4. unpack_goal *) intros tmp_hyp; unpack_goal0 tmp_hyp; clear tmp_hyp; revert_tmp0;
    (* 5. unpack_hyp *)
    evar (tmp_type : Prop);
    let type_of_tmp_self := type of tmp_self in
    assert(tmp_hyp: tmp_type -> type_of_tmp_self);
    [ intros self tmp_hyp; unpack_goal0 tmp_hyp; clear tmp_hyp; revert_tmp0; exact self |
      clear tmp_hyp; assert (self: tmp_type); subst tmp_type;
      [ repeat intro;
        evar (tmp_type: Type); evar (tmp_hyp: tmp_type); subst tmp_type;
        specialize (tmp_self tmp_hyp);
        revert tmp_hyp tmp_self; repeat instantiate (1:= existT _ _ _);
        intros tmp_hyp tmp_self; exact tmp_self
      | clear tmp_self]]
  end.

Ltac pcofix self :=
  let pack_goal0 := idtac in
  let unpack_goal0 _ := idtac in
  let revert_tmp0 := idtac in
  pcofix_ self pack_goal0 unpack_goal0 revert_tmp0.
```

**Comment by gilhur** [comment] 2020-12-28 15:07
I realized that your accumulation lemma `paco3_accF` misses the incremental part `r0 <= r`.
Also I developed a somewhat complex tactic to nicely simplify this incremental assumption, which now I can possibly re-implement  using your "continuation" idea.
I will try it.

**Comment by alxest** [comment] 2020-12-29 09:02
It seems like the new tactic also fixes this issue: https://github.com/snu-sf/paco/issues/34. :+1:

**Comment by gilhur** [comment] 2020-12-29 11:41
I fully implemented this approach and pushed in the branch `remove-jmeq`.
It shows that essentially we can remove the use of the `JMeq_eq` axiom.
However, the problem is that it is too slow due to the use of heavy dependent types.
For example, `gpaco5.v` runs forever at applying the accumulation lemma, so I just generated up to arity 4.
You can generate `gpaco5.v` by changing `maxsize=4` to `maxsize=5` in `metasrc/build.sh`.

If anyone can solve the speed problem, that would be really nice.

**Comment by gilhur** [comment] 2020-12-30 21:19
I did some engineering and now it works reasonably well up to arity 8, though still much slower than the original tactics.
For arity 9 and above, it takes more than a minute at Qed of some proven lemmas.
I think it is still too slow to be merged into the main trunk.

**Comment by minkiminki** [comment] 2021-03-16 00:19
JMeq_eq is removed in #40. It uses n-ary sigma types and doesn't suffer speed issues.

**Comment by Lysxia** [comment] 2021-03-16 00:20
That's great news. Thanks @minkiminki !

**Closed as completed by minkiminki** 2021-03-16 00:19 UTC
Labels: enhancement
